Import('env')

sources = ['InputTests.cpp']

target = env.Program(target=env['target_dir'] + '/test',
                     source=['tests_main.cpp'] + sources + Glob(env['variant_dir'] + '/*.o',
                                                                exclude=[env['variant_dir'] + '/main.o']))

Return('target')
