# langust project source build script
Import('env')

sources = ['Input.cpp', 'Lexer.cpp', 'ParserTable.cpp',
           'Token.cpp', 'Symbol.cpp',
           'ProductionTable.cpp', 'Parser.cpp',
           'ParseTree.cpp', 'ParseTreeBuilder.cpp',
           'ExpressionListener.cpp', 'Ast.cpp',
           'Interpreter.cpp', 'Evaluator.cpp', 'MemoryArena.cpp']

target = env.Program(target=env['target_dir'] + '/langust', source=['main.cpp'] + sources)

Return('target')
