# langust project source build script
Import('env')

sources = ['Input.cpp']
objects = env.Object(sources)

target = env.Program(target=env['target_dir'] + '/prog', source=['main.cpp'] + objects)

Return('target')
